name: pyinstaller-build

on: [push]

jobs:
    pyinstaller-build:
      runs-on: <windows-latest / ubuntu-latest / ..... etc>
      steps:
        - name: Create Executable
          uses: sayyid5416/pyinstaller@v1
          with:
            python_ver: '3.7.9'
            spec: 'src/build.spec'
            upload_exe_with_name: 'csa.exe'
            options: --onefile, --name "csa gui", 